Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,13 +49,40 @@ jobs:
         sleep 10
         curl http://localhost:80
 
-    - name: Install Newman (Postman CLI)
-      run: npm install -g newman
 
-    - name: Run Postman API Tests
+ # Check if application, database and nginx is up and can create Get and Post requests
+    - name: Check - add a new customer 
       run: |
-        newman run ../postman-tests/demo-crm.postman_collection.json 
-        # --reporters cli
+          response=$(curl -s -X POST http://localhost:80/api/clients -H "Content-Type: application/json" -d '{
+            "name": "Shay Danny",
+            "email": "shaydan@develeap.com",
+            "company": "Develeap",
+            "website": "https://shaydan.com"
+          }')
+          echo "Response from POST request: $response"
+          if [[ "$response" != *"success"* ]]; then
+            echo "Failed to add customer."
+            exit 1
+          fi
+
+    - name: Check - show if the customer exists
+      run: |
+          response=$(curl -s http://localhost:80/api/clients)
+          echo "Response from GET request: $response"
+          # Check for the customer name in the response (ensure correct structure)
+          if [[ "$response" == *"Shay Danny"* ]]; then
+            echo "Customer 'Shay Danny' found. Continuing the job."
+          else
+            echo "Customer 'Shay Danny' does not exist. Failing the job."
+            exit 1
+          fi
+
+    # - name: Install Newman (Postman CLI)
+    #   run: npm install -g newman
+
+    # - name: Run Postman API Tests
+    #   run: |
+    #     newman run ../postman-tests/demo-crm.postman_collection.json --reporters cli
 
     - name: Remove testing environment
       run: docker compose down -v
