Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,7 +4,7 @@ on:
     branches:
       - main
 jobs:
-  build_application:
+  CI:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     defaults:
@@ -36,7 +36,7 @@ jobs:
       
         
 #E2E (5)
-    - name: E2E Build the docker-compose
+    - name: Deploy testing environment
       run: docker compose up -d
       
     - name: Check running containers and existed images
@@ -46,9 +46,60 @@ jobs:
         
     - name: wait application to be upload
       run: sleep 5
-      
-    - name: Check application after docker compose
-      run: curl http://localhost:80
+
+    - name: Create character 
+      run: |
+          response=$(curl -s -X POST http://localhost:80/api/clients
+          -H "Content-Type: application/json"
+          -d '{
+            "name": "Koko",
+            "email": "Koko.com",
+            "company": "Koko Dev",
+            "website": "https://Kokothegreat.com"
+          }')
+          echo "Response from POST request: $response"
+          if [[ "$response" != *"Success , Character added"* ]]; then
+            echo "Failure , Failed to add character"
+            exit 1
+          fi
+
+    - name: Character search
+      run: |
+          response=$(curl -s http://localhost:80/api/clients)
+          echo "Response from GET request: $response"
+          # Check for the customer name in the response (ensure correct structure)
+          if [[ "$response" == *"Koko"* ]]; then
+            echo "Success , Character found"
+          else
+            echo "Failure , Character not found"
+            exit 1
+          fi
+
+    # - name: Delete character
+    #   run: |
+    #     response=$(curl --write-out "%{http_code}" --silent --output /dev/null -X DELETE http://localhost:3000/person/1)
+    #     if [ "$response" -ne 200 ]; then
+    #       echo "Failure , Character not deleted"
+    #       exit 1
+    #     else
+    #       echo "Success , Character deleted"
+    #     fi
+
+    - name: Confirm character deletion
+      run: |
+        response=$(curl -s http://localhost:80/api/clients)
+        echo "Response after DELETE: $response"
+
+        if [[ "$response" == *"Koko"* ]]; then
+          echo "Failure , Character exist"
+          exit 1
+        else
+          echo "Success , Character not found"
+        fi
+
+    - name: Remove testing environment
+      run: docker compose down -v
+
       
 # AWS connect
     - name: Configure AWS credentials
